/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ThreadsThreadIdLazyImport = createFileRoute('/threads/threadId')()
const ThreadsNewLazyImport = createFileRoute('/threads/new')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ThreadsThreadIdLazyRoute = ThreadsThreadIdLazyImport.update({
  path: '/threads/threadId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/threads/threadId.lazy').then((d) => d.Route),
)

const ThreadsNewLazyRoute = ThreadsNewLazyImport.update({
  path: '/threads/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/threads/new.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/threads/new': {
      id: '/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ThreadsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/threads/threadId': {
      id: '/threads/threadId'
      path: '/threads/threadId'
      fullPath: '/threads/threadId'
      preLoaderRoute: typeof ThreadsThreadIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ThreadsNewLazyRoute,
  ThreadsThreadIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/threads/new",
        "/threads/threadId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/threads/new": {
      "filePath": "threads/new.lazy.tsx"
    },
    "/threads/threadId": {
      "filePath": "threads/threadId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
