/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewThreadRouteImport } from './routes/newThreadRoute'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ThreadsThreadDetailLazyImport = createFileRoute('/threads/threadDetail')()
const ThreadsNewLazyImport = createFileRoute('/threads/new')()

// Create/Update Routes

const NewThreadRouteRoute = NewThreadRouteImport.update({
  path: '/newThreadRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ThreadsThreadDetailLazyRoute = ThreadsThreadDetailLazyImport.update({
  path: '/threads/threadDetail',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/threads/threadDetail.lazy').then((d) => d.Route),
)

const ThreadsNewLazyRoute = ThreadsNewLazyImport.update({
  path: '/threads/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/threads/new.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/newThreadRoute': {
      id: '/newThreadRoute'
      path: '/newThreadRoute'
      fullPath: '/newThreadRoute'
      preLoaderRoute: typeof NewThreadRouteImport
      parentRoute: typeof rootRoute
    }
    '/threads/new': {
      id: '/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ThreadsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/threads/threadDetail': {
      id: '/threads/threadDetail'
      path: '/threads/threadDetail'
      fullPath: '/threads/threadDetail'
      preLoaderRoute: typeof ThreadsThreadDetailLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  NewThreadRouteRoute,
  ThreadsNewLazyRoute,
  ThreadsThreadDetailLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/newThreadRoute",
        "/threads/new",
        "/threads/threadDetail"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/newThreadRoute": {
      "filePath": "newThreadRoute.tsx"
    },
    "/threads/new": {
      "filePath": "threads/new.lazy.tsx"
    },
    "/threads/threadDetail": {
      "filePath": "threads/threadDetail.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
